### ISSUE TITLE
WinRT & WP8 projects not opening

### ISSUE THREAD

**Issue by vannus** [remobjects/sugar#12]
Opening sugar-master.Sugar.sln using Oxygene trial (compiler version 7.1.75.1557) I get a couple issues:

Sugar.Echoes.WinRT.oxygene is missing a project subtype

![image](https://cloud.githubusercontent.com/assets/6817226/3804576/83a03da6-1c28-11e4-8232-aa8d1ebc6e2d.png)

WindowsPhone Ovverrides.targets not found

![image](https://cloud.githubusercontent.com/assets/6817226/3804594/c2a3e5c0-1c28-11e4-8ab0-96adabd4cb4d.png)

**Comment by carlokok** [comment]
@vannus: Should work now. This basicall requires the winphone sdks to be installed to work
